### GET /eventos
GET http://localhost:8080/eventos
Accept: application/json


### GET /eventos/{id}
GET http://localhost:8080/eventos/5
Accept: application/json


### GET /eventos
http://34.175.190.51:8080/eventos
Accept: application/json
###