apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-catalogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-catalogo
  template:
    metadata:
      labels:
        app: ws-catalogo
    spec:
      serviceAccountName: ksa-backend
      containers:

        - name: ws-catalogo
          image: europe-southwest1-docker.pkg.dev/gestionreservaseventos/repo-eventos/ws-catalogo:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /eventos/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /eventos/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DATABASE_HOST
              value: "127.0.0.1"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "upsa"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "managerDB.1"

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
          args:
            - "--port=5432"
            - "gestionreservaseventos:europe-southwest1:gestion-eventos"
          securityContext:
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: ws-catalogo-service
spec:
  type: LoadBalancer
  selector:
    app: ws-catalogo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080