apiVersion: v1
kind: Secret
metadata:
  name: eventos-db-secret
type: Opaque
stringData:
  POSTGRES_USER: system
  POSTGRES_PASSWORD: manager
  POSTGRES_DB: upsa
---
apiVersion: v1
kind: Service
metadata:
  name: eventos-db-service
spec:
  selector:
    app: eventos-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventos-db
spec:
  serviceName: "eventos-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: eventos-db
  template:
    metadata:
      labels:
        app: eventos-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: eventos-db-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-script
          configMap:
            name: eventos-db-init
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi